"""Compatibility exports for the kernel package."""
from __future__ import annotations

from importlib import import_module

__all__ = [
    "ActorIdentity", "ActorPosition", "ActorRecord", "Action", "AreaDef", "AreaState", "AttackRoll",
    "ArmorInteraction", "BloodState", "BodyPartDef", "BodyPartState", "BodyPlanDef", "BodyState",
    "ColonyPressureState", "ConditionRecord", "CombatResult", "CombatHeader", "ContainerDef",
    "CastingAttempt", "ClassDef", "DefenseProfile", "DialogAction", "DialogCondition", "DialogDef",
    "DialogState", "DialogStateNode", "DialogTransition", "DifficultySettings", "DoorDef", "EffectDef",
    "EffectInstance", "EffectQueue", "EquipmentLoadout", "EquipmentWearUpdate", "FactionRecord",
    "FluidCell", "FluidState", "HistoryEvent", "HistoryFigure", "ItemDef", "ItemInstance",
    "ItemRequirements", "ItemStack", "JobRecord", "JournalEntry", "LegacyItemDef", "LegacyItemStack",
    "LevelUpResult", "LocalActionResolution", "LocalMapState", "MaterialDemand", "MaterialRequirement",
    "MaterialDef", "InfectionState", "MoraleCascade", "MoraleState", "MORALE_CASCADE_TIERS",
    "MacroStateView", "MilitaryState", "NeedDef", "NeedState", "NEED_DEFS", "PainState",
    "PathAuthorityState", "PathResult", "PermanentConsequence", "ProductOutput", "ProductionLedger",
    "GameState", "PowerNetworkState", "PowerNodeState", "ProgressionState", "ProjectileDef",
    "ProjectileInstance", "QuestSeed", "RegionDef", "SearchMap", "RegionRecord", "RecoveryState",
    "ReactionDef", "RoomZoneDef", "RoomDef", "RoundAttackSchedule", "ScriptBlock", "ScriptDef",
    "ScriptState", "ScheduleEntry", "ScheduleState", "SettlementRecord", "SiteRecord", "SpellDef",
    "SpellSlot", "Spellbook", "StrangeMoodIncident", "StoreDef", "StoreItem", "StoreService",
    "SpawnPointDef", "TilePassability", "SquadMemberRecord", "SquadRecord", "StrikeResolution",
    "SyndromeDef", "SyndromeEffect", "SkillRecord", "SKILL_LEVEL_NAMES", "SKILL_XP_THRESHOLDS",
    "Trigger", "WorldTime", "JOB_SKILL_LEVEL_NAMES", "JOB_SKILL_XP_THRESHOLDS", "QUALITY_LEVELS",
    "ROOM_ZONE_DEFS", "TemperatureState", "TissueLayerDef", "TravelEdge", "TravelState",
    "TrapComponent", "TrapState", "TreatmentRecord", "TreatmentRequirement", "TreatmentStep",
    "TREATMENT_REQUIREMENTS", "MovementState", "WorldState", "WorksiteRecord", "WoundRecord",
    "actor_record_from_character", "actor_record_from_entity", "apply_effect", "apply_item_wear",
    "apply_morale_cascade", "apply_permanent_consequence", "apply_room_assignment_bonus",
    "apply_squad_orders", "apply_syndrome", "add_journal_entry", "add_to_party", "advance_local_action",
    "advance_time", "assign_labor", "assign_room", "award_skill_xp", "award_xp", "adjust_store_prices",
    "actors_along_line", "actors_in_cone", "actors_in_radius", "attempt_bump", "begin_casting",
    "buy_healing", "buy_identification", "buy_item", "buy_repair", "bypasses_weapon_immunity",
    "can_level_up", "can_equip", "can_stack", "can_perform_step", "cancel_job", "check_region_entry",
    "check_resistance", "check_drowning", "check_lethal_conditions", "check_morale",
    "check_magma_damage", "check_trap_triggers", "colony_pressure_from_settlement", "compute_mood",
    "compute_attack_roll", "compute_attacks_per_round", "compute_bab", "compute_buy_price",
    "compute_movement_speed", "compute_npc_reaction", "compute_power_network", "compute_room_quality",
    "compute_defense_ac", "compute_encumbrance", "compute_effective_stat", "compute_item_wear",
    "compute_max_spell_slots", "compute_saves", "compute_sell_price", "complete_travel", "complete_job",
    "dispel_effects", "determine_treatment_plan", "decay_needs", "derive_seed", "day_night_state",
    "execute_level_up", "evaluate_condition", "evaluate_script_block", "evaluate_trigger",
    "execute_dialog_action", "execute_action", "fulfill_need", "get_skill_level", "get_skill_level_name",
    "get_global_variable", "get_latest_stage", "get_quest_entries", "hydrate_local_map", "identify_item",
    "initiate_travel", "item_stack_from_legacy_payload", "job_records_from_settlement",
    "local_map_state_from_region", "learn_spell", "launch_projectile", "level_from_xp",
    "material_def_from_legacy_name", "macro_state_from_world", "military_state_from_settlement",
    "modify_reputation", "find_path", "open_container", "open_door", "path_authority_from_world",
    "power_network_from_settlement", "pressure_tags_from_metrics", "production_ledger_from_settlement",
    "create_game_state", "create_artifact", "quest_seeds_from_shortages", "reaction_defs_from_settlement",
    "resolve_attack", "resolve_combat_round", "resolve_cast", "resolve_impact", "resolve_target",
    "resolve_strike", "resolve_saving_throw", "resolve_trap_damage", "rest_refresh_spellbook",
    "rent_room", "random_walk_target", "create_treatment_record", "perform_treatment_step",
    "strange_mood_incident_from_settlement", "get_available_transitions", "select_transition",
    "start_dialog", "spread_contagion", "syndrome_registry_from_actors", "surgery_failure_chance",
    "sync_body_state_to_tracker", "tick_effects", "tick_blood_loss", "tick_casting", "tick_infection",
    "tick_job", "tick_fluids", "tick_movement", "tick_projectile", "tick_strange_mood", "tick_spawns",
    "tick_script", "tick_syndromes", "tick_temperature", "tick_pain", "tick_recovery", "tick_skill_rust",
    "temperature_state_from_region", "tick_travel", "toggle_gear", "trap_state_from_settlement",
    "sell_item", "set_difficulty", "set_global_variable", "swap_party_member", "transition_area",
    "attempt_steal", "unequip_item", "use_item", "equip_item", "fluid_state_from_region",
    "room_morale_bonus", "validate_room_zone", "weighted_random_quality", "worksite_records_from_settlement",
    "world_state_from_blueprint", "travel_options_for_region", "update_fog_of_war", "remove_from_party",
    "FORMATIONS",
]

_EXPORT_LOOKUP = {
    "ActorIdentity": ("engine.kernel.actor", "ActorIdentity"),
    "ActorPosition": ("engine.kernel.actor", "ActorPosition"),
    "ActorRecord": ("engine.kernel.actor", "ActorRecord"),
    "Action": ("engine.kernel.scripts", "Action"),
    "AreaDef": ("engine.kernel.area", "AreaDef"),
    "AreaState": ("engine.kernel.area", "AreaState"),
    "AttackRoll": ("engine.kernel.combat", "AttackRoll"),
    "ArmorInteraction": ("engine.kernel.combat", "ArmorInteraction"),
    "BloodState": ("engine.kernel.combat", "BloodState"),
    "BodyPartDef": ("engine.kernel.actor", "BodyPartDef"),
    "BodyPartState": ("engine.kernel.actor", "BodyPartState"),
    "BodyPlanDef": ("engine.kernel.actor", "BodyPlanDef"),
    "BodyState": ("engine.kernel.actor", "BodyState"),
    "ColonyPressureState": ("engine.kernel.colony", "ColonyPressureState"),
    "ConditionRecord": ("engine.kernel.actor", "ConditionRecord"),
    "CombatResult": ("engine.kernel.combat", "CombatResult"),
    "CombatHeader": ("engine.kernel.items", "CombatHeader"),
    "ContainerDef": ("engine.kernel.area", "ContainerDef"),
    "CastingAttempt": ("engine.kernel.spells", "CastingAttempt"),
    "ClassDef": ("engine.kernel.progression", "ClassDef"),
    "DefenseProfile": ("engine.kernel.combat", "DefenseProfile"),
    "DialogAction": ("engine.kernel.dialog", "DialogAction"),
    "DialogCondition": ("engine.kernel.dialog", "DialogCondition"),
    "DialogDef": ("engine.kernel.dialog", "DialogDef"),
    "DialogState": ("engine.kernel.dialog", "DialogState"),
    "DialogStateNode": ("engine.kernel.dialog", "DialogStateNode"),
    "DialogTransition": ("engine.kernel.dialog", "DialogTransition"),
    "DifficultySettings": ("engine.kernel.game_state", "DifficultySettings"),
    "DoorDef": ("engine.kernel.area", "DoorDef"),
    "EffectDef": ("engine.kernel.effects", "EffectDef"),
    "EffectInstance": ("engine.kernel.effects", "EffectInstance"),
    "EffectQueue": ("engine.kernel.effects", "EffectQueue"),
    "EquipmentLoadout": ("engine.kernel.actor", "EquipmentLoadout"),
    "EquipmentWearUpdate": ("engine.kernel.combat", "EquipmentWearUpdate"),
    "FactionRecord": ("engine.kernel.world_state", "FactionRecord"),
    "FluidCell": ("engine.kernel.systems", "FluidCell"),
    "FluidState": ("engine.kernel.systems", "FluidState"),
    "HistoryEvent": ("engine.kernel.world_state", "HistoryEvent"),
    "HistoryFigure": ("engine.kernel.world_state", "HistoryFigure"),
    "ItemDef": ("engine.kernel.items", "ItemDef"),
    "ItemInstance": ("engine.kernel.items", "ItemInstance"),
    "ItemRequirements": ("engine.kernel.items", "ItemRequirements"),
    "ItemStack": ("engine.kernel.actor", "ItemStack"),
    "JobRecord": ("engine.kernel.jobs", "JobRecord"),
    "JournalEntry": ("engine.kernel.game_state", "JournalEntry"),
    "LegacyItemDef": ("engine.kernel.actor", "ItemDef"),
    "LegacyItemStack": ("engine.kernel.actor", "ItemStack"),
    "LevelUpResult": ("engine.kernel.progression", "LevelUpResult"),
    "LocalActionResolution": ("engine.kernel.hybrid", "LocalActionResolution"),
    "LocalMapState": ("engine.kernel.hybrid", "LocalMapState"),
    "MaterialDemand": ("engine.kernel.systems", "MaterialDemand"),
    "MaterialRequirement": ("engine.kernel.jobs", "MaterialRequirement"),
    "MaterialDef": ("engine.kernel.actor", "MaterialDef"),
    "InfectionState": ("engine.kernel.medical", "InfectionState"),
    "MoraleCascade": ("engine.kernel.colony", "MoraleCascade"),
    "MoraleState": ("engine.kernel.combat", "MoraleState"),
    "MORALE_CASCADE_TIERS": ("engine.kernel.colony", "MORALE_CASCADE_TIERS"),
    "MacroStateView": ("engine.kernel.hybrid", "MacroStateView"),
    "MilitaryState": ("engine.kernel.hybrid", "MilitaryState"),
    "NeedDef": ("engine.kernel.colony", "NeedDef"),
    "NeedState": ("engine.kernel.actor", "NeedState"),
    "NEED_DEFS": ("engine.kernel.colony", "NEED_DEFS"),
    "PainState": ("engine.kernel.combat", "PainState"),
    "PathAuthorityState": ("engine.kernel.hybrid", "PathAuthorityState"),
    "PathResult": ("engine.kernel.pathfinding", "PathResult"),
    "PermanentConsequence": ("engine.kernel.medical", "PermanentConsequence"),
    "ProductOutput": ("engine.kernel.jobs", "ProductOutput"),
    "ProductionLedger": ("engine.kernel.colony", "ProductionLedger"),
    "GameState": ("engine.kernel.game_state", "GameState"),
    "PowerNetworkState": ("engine.kernel.systems", "PowerNetworkState"),
    "PowerNodeState": ("engine.kernel.systems", "PowerNodeState"),
    "ProgressionState": ("engine.kernel.progression", "ProgressionState"),
    "ProjectileDef": ("engine.kernel.projectiles", "ProjectileDef"),
    "ProjectileInstance": ("engine.kernel.projectiles", "ProjectileInstance"),
    "QuestSeed": ("engine.kernel.colony", "QuestSeed"),
    "RegionDef": ("engine.kernel.area", "RegionDef"),
    "SearchMap": ("engine.kernel.pathfinding", "SearchMap"),
    "RegionRecord": ("engine.kernel.world_state", "RegionRecord"),
    "RecoveryState": ("engine.kernel.medical", "RecoveryState"),
    "ReactionDef": ("engine.kernel.jobs", "ReactionDef"),
    "RoomZoneDef": ("engine.kernel.jobs", "RoomZoneDef"),
    "RoomDef": ("engine.kernel.area", "RoomDef"),
    "RoundAttackSchedule": ("engine.kernel.combat", "RoundAttackSchedule"),
    "ScriptBlock": ("engine.kernel.scripts", "ScriptBlock"),
    "ScriptDef": ("engine.kernel.scripts", "ScriptDef"),
    "ScriptState": ("engine.kernel.scripts", "ScriptState"),
    "ScheduleEntry": ("engine.kernel.actor", "ScheduleEntry"),
    "ScheduleState": ("engine.kernel.actor", "ScheduleState"),
    "SettlementRecord": ("engine.kernel.world_state", "SettlementRecord"),
    "SiteRecord": ("engine.kernel.world_state", "SiteRecord"),
    "SpellDef": ("engine.kernel.spells", "SpellDef"),
    "SpellSlot": ("engine.kernel.spells", "SpellSlot"),
    "Spellbook": ("engine.kernel.spells", "Spellbook"),
    "StrangeMoodIncident": ("engine.kernel.systems", "StrangeMoodIncident"),
    "StoreDef": ("engine.kernel.store", "StoreDef"),
    "StoreItem": ("engine.kernel.store", "StoreItem"),
    "StoreService": ("engine.kernel.store", "StoreService"),
    "SpawnPointDef": ("engine.kernel.area", "SpawnPointDef"),
    "TilePassability": ("engine.kernel.pathfinding", "TilePassability"),
    "SquadMemberRecord": ("engine.kernel.hybrid", "SquadMemberRecord"),
    "SquadRecord": ("engine.kernel.hybrid", "SquadRecord"),
    "StrikeResolution": ("engine.kernel.combat", "StrikeResolution"),
    "SyndromeDef": ("engine.kernel.systems", "SyndromeDef"),
    "SyndromeEffect": ("engine.kernel.systems", "SyndromeEffect"),
    "SkillRecord": ("engine.kernel.jobs", "SkillRecord"),
    "SKILL_LEVEL_NAMES": ("engine.kernel.progression", "SKILL_LEVEL_NAMES"),
    "SKILL_XP_THRESHOLDS": ("engine.kernel.progression", "SKILL_XP_THRESHOLDS"),
    "Trigger": ("engine.kernel.scripts", "Trigger"),
    "WorldTime": ("engine.kernel.game_state", "WorldTime"),
    "JOB_SKILL_LEVEL_NAMES": ("engine.kernel.jobs", "SKILL_LEVEL_NAMES"),
    "JOB_SKILL_XP_THRESHOLDS": ("engine.kernel.jobs", "SKILL_XP_THRESHOLDS"),
    "QUALITY_LEVELS": ("engine.kernel.jobs", "QUALITY_LEVELS"),
    "ROOM_ZONE_DEFS": ("engine.kernel.jobs", "ROOM_ZONE_DEFS"),
    "TemperatureState": ("engine.kernel.systems", "TemperatureState"),
    "TissueLayerDef": ("engine.kernel.actor", "TissueLayerDef"),
    "TravelEdge": ("engine.kernel.world_state", "TravelEdge"),
    "TravelState": ("engine.kernel.hybrid", "TravelState"),
    "TrapComponent": ("engine.kernel.systems", "TrapComponent"),
    "TrapState": ("engine.kernel.systems", "TrapState"),
    "TreatmentRecord": ("engine.kernel.medical", "TreatmentRecord"),
    "TreatmentRequirement": ("engine.kernel.medical", "TreatmentRequirement"),
    "TreatmentStep": ("engine.kernel.medical", "TreatmentStep"),
    "TREATMENT_REQUIREMENTS": ("engine.kernel.medical", "TREATMENT_REQUIREMENTS"),
    "MovementState": ("engine.kernel.pathfinding", "MovementState"),
    "WorldState": ("engine.kernel.world_state", "WorldState"),
    "WorksiteRecord": ("engine.kernel.jobs", "WorksiteRecord"),
    "WoundRecord": ("engine.kernel.actor", "WoundRecord"),
    "actor_record_from_character": ("engine.kernel.actor", "actor_record_from_character"),
    "actor_record_from_entity": ("engine.kernel.actor", "actor_record_from_entity"),
    "apply_effect": ("engine.kernel.effects", "apply_effect"),
    "apply_item_wear": ("engine.kernel.items", "apply_item_wear"),
    "apply_morale_cascade": ("engine.kernel.colony", "apply_morale_cascade"),
    "apply_permanent_consequence": ("engine.kernel.medical", "apply_permanent_consequence"),
    "apply_room_assignment_bonus": ("engine.kernel.area", "apply_room_assignment_bonus"),
    "apply_squad_orders": ("engine.kernel.hybrid", "apply_squad_orders"),
    "apply_syndrome": ("engine.kernel.systems", "apply_syndrome"),
    "add_journal_entry": ("engine.kernel.game_state", "add_journal_entry"),
    "add_to_party": ("engine.kernel.game_state", "add_to_party"),
    "advance_local_action": ("engine.kernel.hybrid", "advance_local_action"),
    "advance_time": ("engine.kernel.game_state", "advance_time"),
    "assign_labor": ("engine.kernel.jobs", "assign_labor"),
    "assign_room": ("engine.kernel.area", "assign_room"),
    "award_skill_xp": ("engine.kernel.progression", "award_skill_xp"),
    "award_xp": ("engine.kernel.progression", "award_xp"),
    "adjust_store_prices": ("engine.kernel.store", "adjust_store_prices"),
    "actors_along_line": ("engine.kernel.projectiles", "actors_along_line"),
    "actors_in_cone": ("engine.kernel.projectiles", "actors_in_cone"),
    "actors_in_radius": ("engine.kernel.projectiles", "actors_in_radius"),
    "attempt_bump": ("engine.kernel.pathfinding", "attempt_bump"),
    "begin_casting": ("engine.kernel.spells", "begin_casting"),
    "buy_healing": ("engine.kernel.store", "buy_healing"),
    "buy_identification": ("engine.kernel.store", "buy_identification"),
    "buy_item": ("engine.kernel.store", "buy_item"),
    "buy_repair": ("engine.kernel.store", "buy_repair"),
    "bypasses_weapon_immunity": ("engine.kernel.items", "bypasses_weapon_immunity"),
    "can_level_up": ("engine.kernel.progression", "can_level_up"),
    "can_equip": ("engine.kernel.items", "can_equip"),
    "can_stack": ("engine.kernel.items", "can_stack"),
    "can_perform_step": ("engine.kernel.medical", "can_perform_step"),
    "cancel_job": ("engine.kernel.jobs", "cancel_job"),
    "check_region_entry": ("engine.kernel.area", "check_region_entry"),
    "check_resistance": ("engine.kernel.effects", "check_resistance"),
    "check_drowning": ("engine.kernel.systems", "check_drowning"),
    "check_lethal_conditions": ("engine.kernel.medical", "check_lethal_conditions"),
    "check_morale": ("engine.kernel.combat", "check_morale"),
    "check_magma_damage": ("engine.kernel.systems", "check_magma_damage"),
    "check_trap_triggers": ("engine.kernel.systems", "check_trap_triggers"),
    "colony_pressure_from_settlement": ("engine.kernel.colony", "colony_pressure_from_settlement"),
    "compute_mood": ("engine.kernel.colony", "compute_mood"),
    "compute_attack_roll": ("engine.kernel.combat", "compute_attack_roll"),
    "compute_attacks_per_round": ("engine.kernel.combat", "compute_attacks_per_round"),
    "compute_bab": ("engine.kernel.progression", "compute_bab"),
    "compute_buy_price": ("engine.kernel.store", "compute_buy_price"),
    "compute_movement_speed": ("engine.kernel.pathfinding", "compute_movement_speed"),
    "compute_npc_reaction": ("engine.kernel.dialog", "compute_npc_reaction"),
    "compute_power_network": ("engine.kernel.systems", "compute_power_network"),
    "compute_room_quality": ("engine.kernel.area", "compute_room_quality"),
    "compute_defense_ac": ("engine.kernel.combat", "compute_defense_ac"),
    "compute_encumbrance": ("engine.kernel.items", "compute_encumbrance"),
    "compute_effective_stat": ("engine.kernel.effects", "compute_effective_stat"),
    "compute_item_wear": ("engine.kernel.items", "compute_item_wear"),
    "compute_max_spell_slots": ("engine.kernel.spells", "compute_max_spell_slots"),
    "compute_saves": ("engine.kernel.progression", "compute_saves"),
    "compute_sell_price": ("engine.kernel.store", "compute_sell_price"),
    "complete_travel": ("engine.kernel.hybrid", "complete_travel"),
    "complete_job": ("engine.kernel.jobs", "complete_job"),
    "dispel_effects": ("engine.kernel.effects", "dispel_effects"),
    "determine_treatment_plan": ("engine.kernel.medical", "determine_treatment_plan"),
    "decay_needs": ("engine.kernel.colony", "decay_needs"),
    "derive_seed": ("engine.kernel.game_state", "derive_seed"),
    "day_night_state": ("engine.kernel.area", "day_night_state"),
    "execute_level_up": ("engine.kernel.progression", "execute_level_up"),
    "evaluate_condition": ("engine.kernel.dialog", "evaluate_condition"),
    "evaluate_script_block": ("engine.kernel.scripts", "evaluate_script_block"),
    "evaluate_trigger": ("engine.kernel.scripts", "evaluate_trigger"),
    "execute_dialog_action": ("engine.kernel.dialog", "execute_dialog_action"),
    "execute_action": ("engine.kernel.scripts", "execute_action"),
    "fulfill_need": ("engine.kernel.colony", "fulfill_need"),
    "get_skill_level": ("engine.kernel.progression", "get_skill_level"),
    "get_skill_level_name": ("engine.kernel.progression", "get_skill_level_name"),
    "get_global_variable": ("engine.kernel.game_state", "get_global_variable"),
    "get_latest_stage": ("engine.kernel.game_state", "get_latest_stage"),
    "get_quest_entries": ("engine.kernel.game_state", "get_quest_entries"),
    "hydrate_local_map": ("engine.kernel.hybrid", "hydrate_local_map"),
    "identify_item": ("engine.kernel.items", "identify_item"),
    "initiate_travel": ("engine.kernel.hybrid", "initiate_travel"),
    "item_stack_from_legacy_payload": ("engine.kernel.actor", "item_stack_from_legacy_payload"),
    "job_records_from_settlement": ("engine.kernel.jobs", "job_records_from_settlement"),
    "local_map_state_from_region": ("engine.kernel.hybrid", "local_map_state_from_region"),
    "learn_spell": ("engine.kernel.spells", "learn_spell"),
    "launch_projectile": ("engine.kernel.projectiles", "launch_projectile"),
    "level_from_xp": ("engine.kernel.jobs", "level_from_xp"),
    "material_def_from_legacy_name": ("engine.kernel.combat", "material_def_from_legacy_name"),
    "macro_state_from_world": ("engine.kernel.hybrid", "macro_state_from_world"),
    "military_state_from_settlement": ("engine.kernel.hybrid", "military_state_from_settlement"),
    "modify_reputation": ("engine.kernel.game_state", "modify_reputation"),
    "find_path": ("engine.kernel.pathfinding", "find_path"),
    "open_container": ("engine.kernel.area", "open_container"),
    "open_door": ("engine.kernel.area", "open_door"),
    "path_authority_from_world": ("engine.kernel.hybrid", "path_authority_from_world"),
    "power_network_from_settlement": ("engine.kernel.systems", "power_network_from_settlement"),
    "pressure_tags_from_metrics": ("engine.kernel.colony", "pressure_tags_from_metrics"),
    "production_ledger_from_settlement": ("engine.kernel.colony", "production_ledger_from_settlement"),
    "create_game_state": ("engine.kernel.game_state", "create_game_state"),
    "create_artifact": ("engine.kernel.systems", "create_artifact"),
    "quest_seeds_from_shortages": ("engine.kernel.colony", "quest_seeds_from_shortages"),
    "reaction_defs_from_settlement": ("engine.kernel.jobs", "reaction_defs_from_settlement"),
    "resolve_attack": ("engine.kernel.combat", "resolve_attack"),
    "resolve_combat_round": ("engine.kernel.combat", "resolve_combat_round"),
    "resolve_cast": ("engine.kernel.spells", "resolve_cast"),
    "resolve_impact": ("engine.kernel.projectiles", "resolve_impact"),
    "resolve_target": ("engine.kernel.scripts", "resolve_target"),
    "resolve_strike": ("engine.kernel.combat", "resolve_strike"),
    "resolve_saving_throw": ("engine.kernel.effects", "resolve_saving_throw"),
    "resolve_trap_damage": ("engine.kernel.systems", "resolve_trap_damage"),
    "rest_refresh_spellbook": ("engine.kernel.spells", "rest_refresh_spellbook"),
    "rent_room": ("engine.kernel.store", "rent_room"),
    "random_walk_target": ("engine.kernel.pathfinding", "random_walk_target"),
    "create_treatment_record": ("engine.kernel.medical", "create_treatment_record"),
    "perform_treatment_step": ("engine.kernel.medical", "perform_treatment_step"),
    "strange_mood_incident_from_settlement": ("engine.kernel.systems", "strange_mood_incident_from_settlement"),
    "get_available_transitions": ("engine.kernel.dialog", "get_available_transitions"),
    "select_transition": ("engine.kernel.dialog", "select_transition"),
    "start_dialog": ("engine.kernel.dialog", "start_dialog"),
    "spread_contagion": ("engine.kernel.systems", "spread_contagion"),
    "syndrome_registry_from_actors": ("engine.kernel.systems", "syndrome_registry_from_actors"),
    "surgery_failure_chance": ("engine.kernel.medical", "surgery_failure_chance"),
    "sync_body_state_to_tracker": ("engine.kernel.actor", "sync_body_state_to_tracker"),
    "tick_effects": ("engine.kernel.effects", "tick_effects"),
    "tick_blood_loss": ("engine.kernel.combat", "tick_blood_loss"),
    "tick_casting": ("engine.kernel.spells", "tick_casting"),
    "tick_infection": ("engine.kernel.medical", "tick_infection"),
    "tick_job": ("engine.kernel.jobs", "tick_job"),
    "tick_fluids": ("engine.kernel.systems", "tick_fluids"),
    "tick_movement": ("engine.kernel.pathfinding", "tick_movement"),
    "tick_projectile": ("engine.kernel.projectiles", "tick_projectile"),
    "tick_strange_mood": ("engine.kernel.systems", "tick_strange_mood"),
    "tick_spawns": ("engine.kernel.area", "tick_spawns"),
    "tick_script": ("engine.kernel.scripts", "tick_script"),
    "tick_syndromes": ("engine.kernel.systems", "tick_syndromes"),
    "tick_temperature": ("engine.kernel.systems", "tick_temperature"),
    "tick_pain": ("engine.kernel.combat", "tick_pain"),
    "tick_recovery": ("engine.kernel.medical", "tick_recovery"),
    "tick_skill_rust": ("engine.kernel.jobs", "tick_skill_rust"),
    "temperature_state_from_region": ("engine.kernel.systems", "temperature_state_from_region"),
    "tick_travel": ("engine.kernel.hybrid", "tick_travel"),
    "toggle_gear": ("engine.kernel.systems", "toggle_gear"),
    "trap_state_from_settlement": ("engine.kernel.systems", "trap_state_from_settlement"),
    "sell_item": ("engine.kernel.store", "sell_item"),
    "set_difficulty": ("engine.kernel.game_state", "set_difficulty"),
    "set_global_variable": ("engine.kernel.game_state", "set_global_variable"),
    "swap_party_member": ("engine.kernel.game_state", "swap_party_member"),
    "transition_area": ("engine.kernel.area", "transition_area"),
    "attempt_steal": ("engine.kernel.store", "attempt_steal"),
    "unequip_item": ("engine.kernel.items", "unequip_item"),
    "use_item": ("engine.kernel.items", "use_item"),
    "equip_item": ("engine.kernel.items", "equip_item"),
    "fluid_state_from_region": ("engine.kernel.systems", "fluid_state_from_region"),
    "room_morale_bonus": ("engine.kernel.colony", "room_morale_bonus"),
    "validate_room_zone": ("engine.kernel.jobs", "validate_room_zone"),
    "weighted_random_quality": ("engine.kernel.jobs", "weighted_random_quality"),
    "worksite_records_from_settlement": ("engine.kernel.jobs", "worksite_records_from_settlement"),
    "world_state_from_blueprint": ("engine.kernel.world_state", "world_state_from_blueprint"),
    "travel_options_for_region": ("engine.kernel.hybrid", "travel_options_for_region"),
    "update_fog_of_war": ("engine.kernel.area", "update_fog_of_war"),
    "remove_from_party": ("engine.kernel.game_state", "remove_from_party"),
    "FORMATIONS": ("engine.kernel.game_state", "FORMATIONS"),
}


def __getattr__(name: str):
    if name not in _EXPORT_LOOKUP:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _EXPORT_LOOKUP[name]
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value
